#!/usr/bin/env bash
# Dependency Update Skill Script
# Checks for outdated dependencies and creates a PR with updates
# Compatible with the openai-agents-python project structure

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
BRANCH_PREFIX="chore/dependency-update"
DATE_SUFFIX="$(date +%Y%m%d)"
UPDATE_BRANCH="${BRANCH_PREFIX}-${DATE_SUFFIX}"

# Colours for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Colour

log_info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ---------------------------------------------------------------------------
# Prerequisite checks
# ---------------------------------------------------------------------------
check_prerequisites() {
    local missing=0

    for cmd in python pip git; do
        if ! command -v "$cmd" &>/dev/null; then
            log_error "Required command not found: $cmd"
            missing=1
        fi
    done

    if [[ $missing -eq 1 ]]; then
        exit 1
    fi

    log_info "All prerequisites satisfied."
}

# ---------------------------------------------------------------------------
# Fetch outdated packages using pip
# ---------------------------------------------------------------------------
get_outdated_packages() {
    log_info "Checking for outdated packages..."
    # Returns JSON array: [{"name": "pkg", "version": "x", "latest_version": "y"}, ...]
    python -m pip list --outdated --format=json 2>/dev/null
}

# ---------------------------------------------------------------------------
# Update pyproject.toml / requirements files
# ---------------------------------------------------------------------------
update_dependencies() {
    local outdated_json="$1"

    if [[ -z "$outdated_json" || "$outdated_json" == "[]" ]]; then
        log_info "All dependencies are up to date. Nothing to do."
        return 0
    fi

    log_info "Upgrading outdated packages..."
    # Upgrade each package individually so failures are isolated
    echo "$outdated_json" | python - <<'PYEOF'
import json, subprocess, sys

data = json.load(sys.stdin)
for pkg in data:
    name = pkg["name"]
    latest = pkg["latest_version"]
    print(f"  Upgrading {name} -> {latest}")
    result = subprocess.run(
        ["pip", "install", "--upgrade", name],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"  [WARN] Failed to upgrade {name}: {result.stderr.strip()}", file=sys.stderr)
PYEOF

    # Sync lock file if uv is available
    if command -v uv &>/dev/null; then
        log_info "Syncing lock file with uv..."
        (cd "$PROJECT_ROOT" && uv lock) || log_warn "uv lock failed; continuing without lock update."
    fi

    return 0
}

# ---------------------------------------------------------------------------
# Git operations
# ---------------------------------------------------------------------------
create_update_branch() {
    log_info "Creating branch: ${UPDATE_BRANCH}"
    git -C "$PROJECT_ROOT" checkout -b "$UPDATE_BRANCH" 2>/dev/null || {
        log_warn "Branch already exists; checking it out."
        git -C "$PROJECT_ROOT" checkout "$UPDATE_BRANCH"
    }
}

commit_changes() {
    local outdated_json="$1"

    cd "$PROJECT_ROOT"

    if git diff --quiet && git diff --cached --quiet; then
        log_info "No file changes detected; skipping commit."
        return 0
    fi

    # Build a concise commit body listing updated packages
    local body
    body=$(echo "$outdated_json" | python - <<'PYEOF'
import json, sys
data = json.load(sys.stdin)
lines = [f"- {p['name']}: {p['version']} -> {p['latest_version']}" for p in data]
print("\n".join(lines))
PYEOF
    )

    git add -A
    git commit -m "chore(deps): bump outdated dependencies ${DATE_SUFFIX}" \
               -m "${body}"
    log_info "Changes committed."
}

# ---------------------------------------------------------------------------
# Optional: open a GitHub PR via gh CLI
# ---------------------------------------------------------------------------
open_pull_request() {
    if ! command -v gh &>/dev/null; then
        log_warn "gh CLI not found; skipping PR creation."
        return 0
    fi

    log_info "Pushing branch and opening PR..."
    git -C "$PROJECT_ROOT" push --set-upstream origin "$UPDATE_BRANCH" || {
        log_error "Push failed."
        return 1
    }

    gh pr create \
        --title "chore(deps): bump outdated dependencies ${DATE_SUFFIX}" \
        --body "Automated dependency update generated by the dependency-update skill." \
        --base main \
        --head "$UPDATE_BRANCH" \
        --label "dependencies" || log_warn "PR creation failed (may already exist)."
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    log_info "Starting dependency update skill (project: ${PROJECT_ROOT})"

    check_prerequisites

    local outdated
    outdated=$(get_outdated_packages)

    create_update_branch
    update_dependencies "$outdated"
    commit_changes "$outdated"

    # Only push / open PR when running in CI or when explicitly requested
    if [[ "${CI:-false}" == "true" || "${OPEN_PR:-false}" == "true" ]]; then
        open_pull_request
    else
        log_info "Skipping PR creation (set OPEN_PR=true or run in CI to enable)."
    fi

    log_info "Dependency update skill completed successfully."
}

main "$@"
